apiVersion: v1
kind: Pod
metadata:
  name: mongodb
spec:
  containers:
    - name: mongodb
      image: mongo
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 27017
          protocol: TCP
      volumeMounts:
        - name: monogdb-data
          mountPath: /data/db
  volumes:
    - name: monogdb-data
      persistentVolumeClaim:
        claimName: mongodb-pvc
