apiVersion: v1
kind: Pod
metadata:
  name: fortune-env
spec:
  containers:
    - name: html-generator
      image: kyungrae/fortune:env
      env:
        - name: INTERVAL
          value: "30"
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
      volumeMounts:
        - name: html
          mountPath: /var/htdocs
    - name: web-server
      image: nginx:alpine
      resources:
        limits:
          memory: "64Mi"
          cpu: "250m"
      ports:
        - containerPort: 80
          protocol: TCP
      volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
          readOnly: true
  volumes:
    - name: html
      emptyDir: {}
