version: '3.8'

services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - spring-batch-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hama
      MYSQL_DATABASE: spring_batch

volumes:
  spring-batch-data:
