spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      acks: all
    consumer:
      bootstrap-server: localhost:9092
    listener:
      ack-mode: MANUAL_IMMEDIATE
      type: RECORD
#      type: BATCH
