version: "3.8"

volumes:
  esdata:
    driver: local
  eslogs:
    driver: local

services:
  elasticsearch:
    container_name: test-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.2
    labels:
      co.elastic.logs/module: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - eslogs:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    environment:
      - cluster.name=test-es
      - discovery.type=single-node
      - xpack.security.enabled=false
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200"]
      interval: 10s
      timeout: 10s
      retries: 120
  kibana:
    container_name: test-kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: docker.elastic.co/kibana/kibana:8.4.2
    labels:
      co.elastic.logs/module: kibana
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
