apiVersion: v1
kind: Pod
metadata:
  name: kubia-gpu
spec:
  nodeSelector:
    gpu: "true"
  containers:
    - name: kubia
      image: kyungrae/kubia
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
