apiVersion: batch/v1
kind: Job
metadata:
  name: time-limited-batch-job
spec:
  activeDeadlineSeconds: 30
  ttlSecondsAfterFinished: 10
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      containers:
        - name: main
          image: kyungrae/batch-job
      restartPolicy: Never
