apiVersion: v1
kind: Pod
metadata:
  name: curl-with-ambassador
spec:
  containers:
    - name: main
      image: alpine/curl
      command: ["sleep", "9999999"]
      resources:
        limits:
          memory: "6Mi"
          cpu: "100m"
    - name: ambassador
      image: kyungrae/kubectl-proxy
      resources:
        limits:
          memory: "128Mi"
          cpu: "100m"
